Dyndrop API ctl: Make it use the correct env, launch db:migrate.

diff --git a/jobs/dyndrop_api/templates/dyndrop_api_ctl.erb b/jobs/dyndrop_api/templates/dyndrop_api_ctl.erb
--- a/jobs/dyndrop_api/templates/dyndrop_api_ctl.erb
+++ b/jobs/dyndrop_api/templates/dyndrop_api_ctl.erb
@@ -4,7 +4,7 @@ export DD_JOB_DIR=/var/vcap/jobs/dyndrop_api
 export RAILS_ENV=production
 export PATH=/var/vcap/packages/ruby/bin:$PATH
 
-DD_PACKAGE_DIR=/var/vcap/packages/dyndrop_api
+DD_PACKAGE_DIR=/var/vcap/packages/dyndrop_server
 NFS_SHARE_GIT_REPOS=/var/vcap/dyndrop_api/git_repositories
 NFS_SHARE_REPO_INSTANCES=/var/vcap/dyndrop_api/repo_instances
 
@@ -13,11 +13,15 @@ LOG_DIR=/var/vcap/sys/log/dyndrop_api
 PIDFILE=$RUN_DIR/dyndrop_api.pid
 
 export DYNDROP_API_CONFIG=$DD_JOB_DIR/config/dyndrop_api.yml
-export BUNDLE_GEMFILE=$DD_PACKAGE_DIR/dyndrop_api/Gemfile
+export BUNDLE_GEMFILE=$DD_PACKAGE_DIR/Gemfile
 export HOME=/home/vcap # rake needs it to be set to run tasks
 export TMPDIR=/var/vcap/data/dyndrop_api/tmp
 
 export CONFIG_DIR=$DD_JOB_DIR/config
+
+export RACK_ENV=production
+export DYNDROP_SERVER_DATABASE_CONFIG="/var/vcap/jobs/dyndrop_api/config/dyndrop_api_database.yml"
+export DYNDROP_SERVER_CONFIG="/var/vcap/jobs/dyndrop_api/config/dyndrop_api.yml"
 
 source /var/vcap/packages/common/utils.sh
 
@@ -90,25 +94,19 @@ case $1 in
       exit 1
     fi
 
-
-
-    # Only done on the first CC launch
-    # <% if spec.index.to_i == 0 %>
-    #   cd $DD_PACKAGE_DIR/dyndrop_api
-    #   export CC_NOSTART=1
-    #   chpst -u vcap:vcap bundle exec rake db:migrate >>$LOG_DIR/db_migrate.stdout.log 2>>$LOG_DIR/db_migrate.stderr.log
-    #   if [ $? != 0 ]; then
-    #     echo "Migrations failed"
-    #     # TODO: what to do with other CCs if this failed?
-    #     exit 1
-    #   fi
-    #   unset CC_NOSTART
-    # <% end %>
+    cd $DD_PACKAGE_DIR
+    chpst -u vcap:vcap bundle exec rake db:migrate >>$LOG_DIR/db_migrate.stdout.log 2>>$LOG_DIR/db_migrate.stderr.log
+    if [ $? != 0 ]; then
+      echo "Migrations failed"
+      # TODO: what to do with other CCs if this failed?
+      exit 1
+    fi
 
 
     exec chpst -u vcap:vcap /var/vcap/packages/dyndrop_server/bin/dyndrop-server \
-        -c /var/vcap/jobs/dyndrop_api/config/dyndrop_api.yml
-        -d /var/vcap/jobs/dyndrop_api/config/dyndrop_api_database.yml
+        -c /var/vcap/jobs/dyndrop_api/config/dyndrop_api.yml \
+        -d /var/vcap/jobs/dyndrop_api/config/dyndrop_api_database.yml \
+        -p <%= properties.dyndrop_api.port %> \
         >>$LOG_DIR/dyndrop_api.stdout.log \
         2>>$LOG_DIR/dyndrop_api.stderr.log
 
